// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_gen.proto

package user_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//主从库
type DB int32

const (
	//读库
	DB_READ DB = 0
	//写库
	DB_WRITE DB = 1
)

var DB_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}

var DB_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x DB) String() string {
	return proto.EnumName(DB_name, int32(x))
}

func (DB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{0}
}

type User struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	RealName             string   `protobuf:"bytes,4,opt,name=RealName,proto3" json:"RealName,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Birthday             string   `protobuf:"bytes,6,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Sex                  int32    `protobuf:"varint,7,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	OfficePhone          string   `protobuf:"bytes,9,opt,name=OfficePhone,proto3" json:"OfficePhone,omitempty"`
	HomePhone            string   `protobuf:"bytes,10,opt,name=HomePhone,proto3" json:"HomePhone,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=Email,proto3" json:"Email,omitempty"`
	CreateTime           string   `protobuf:"bytes,12,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	PosIds               string   `protobuf:"bytes,14,opt,name=PosIds,proto3" json:"PosIds,omitempty"`
	Fax                  string   `protobuf:"bytes,15,opt,name=Fax,proto3" json:"Fax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetOfficePhone() string {
	if m != nil {
		return m.OfficePhone
	}
	return ""
}

func (m *User) GetHomePhone() string {
	if m != nil {
		return m.HomePhone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetPosIds() string {
	if m != nil {
		return m.PosIds
	}
	return ""
}

func (m *User) GetFax() string {
	if m != nil {
		return m.Fax
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 按条件更新数据
type UpdateAndCondition struct {
	// 更新数据，如果filed对应为空值，则需要在 update_empty_fields 中声明
	Entity *User `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	//查询条件
	Query *Query `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 需要赋空值的字段 大写字段数组
	UpdateEmptyFields    []string `protobuf:"bytes,3,rep,name=update_empty_fields,json=updateEmptyFields,proto3" json:"update_empty_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAndCondition) Reset()         { *m = UpdateAndCondition{} }
func (m *UpdateAndCondition) String() string { return proto.CompactTextString(m) }
func (*UpdateAndCondition) ProtoMessage()    {}
func (*UpdateAndCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{2}
}

func (m *UpdateAndCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAndCondition.Unmarshal(m, b)
}
func (m *UpdateAndCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAndCondition.Marshal(b, m, deterministic)
}
func (m *UpdateAndCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAndCondition.Merge(m, src)
}
func (m *UpdateAndCondition) XXX_Size() int {
	return xxx_messageInfo_UpdateAndCondition.Size(m)
}
func (m *UpdateAndCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAndCondition.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAndCondition proto.InternalMessageInfo

func (m *UpdateAndCondition) GetEntity() *User {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *UpdateAndCondition) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *UpdateAndCondition) GetUpdateEmptyFields() []string {
	if m != nil {
		return m.UpdateEmptyFields
	}
	return nil
}

//按条件查询
type Query struct {
	// 按照实体查询 （和sql查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	EntityQuery *User `protobuf:"bytes,1,opt,name=entity_query,json=entityQuery,proto3" json:"entity_query,omitempty"`
	// 按照sql查询（和实体查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// "id=1 and status in(3,4) and createtime >'2018' "
	SqlQuery string `protobuf:"bytes,2,opt,name=sql_query,json=sqlQuery,proto3" json:"sql_query,omitempty"`
	// 用空值当检索条件的字段 大写字段数组
	QueryEmptyFields []string `protobuf:"bytes,3,rep,name=query_empty_fields,json=queryEmptyFields,proto3" json:"query_empty_fields,omitempty"`
	//排序条件 key值为数据库字段 ["id":"desc","create_time":asc"]
	OrderBy map[string]string `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//是否查询主库，默认不读取 DB.READ
	Db DB `protobuf:"varint,5,opt,name=db,proto3,enum=user_proto.DB" json:"db,omitempty"`
	//制定select查询的字段，如 "id,username,age"
	SelectField          string   `protobuf:"bytes,6,opt,name=select_field,json=selectField,proto3" json:"select_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{3}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetEntityQuery() *User {
	if m != nil {
		return m.EntityQuery
	}
	return nil
}

func (m *Query) GetSqlQuery() string {
	if m != nil {
		return m.SqlQuery
	}
	return ""
}

func (m *Query) GetQueryEmptyFields() []string {
	if m != nil {
		return m.QueryEmptyFields
	}
	return nil
}

func (m *Query) GetOrderBy() map[string]string {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *Query) GetDb() DB {
	if m != nil {
		return m.Db
	}
	return DB_READ
}

func (m *Query) GetSelectField() string {
	if m != nil {
		return m.SelectField
	}
	return ""
}

//分页查询
type PageQuery struct {
	//查询条件
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{4}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *PageQuery) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageQuery) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type EntityResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityResult) Reset()         { *m = EntityResult{} }
func (m *EntityResult) String() string { return proto.CompactTextString(m) }
func (*EntityResult) ProtoMessage()    {}
func (*EntityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{5}
}

func (m *EntityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityResult.Unmarshal(m, b)
}
func (m *EntityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityResult.Marshal(b, m, deterministic)
}
func (m *EntityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityResult.Merge(m, src)
}
func (m *EntityResult) XXX_Size() int {
	return xxx_messageInfo_EntityResult.Size(m)
}
func (m *EntityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityResult.DiscardUnknown(m)
}

var xxx_messageInfo_EntityResult proto.InternalMessageInfo

func (m *EntityResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EntityResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EntityResult) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*User  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResult) Reset()         { *m = ListResult{} }
func (m *ListResult) String() string { return proto.CompactTextString(m) }
func (*ListResult) ProtoMessage()    {}
func (*ListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{6}
}

func (m *ListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResult.Unmarshal(m, b)
}
func (m *ListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResult.Marshal(b, m, deterministic)
}
func (m *ListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResult.Merge(m, src)
}
func (m *ListResult) XXX_Size() int {
	return xxx_messageInfo_ListResult.Size(m)
}
func (m *ListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListResult proto.InternalMessageInfo

func (m *ListResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResult) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

type PageResult struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserPageData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PageResult) Reset()         { *m = PageResult{} }
func (m *PageResult) String() string { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()    {}
func (*PageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{7}
}

func (m *PageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResult.Unmarshal(m, b)
}
func (m *PageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResult.Marshal(b, m, deterministic)
}
func (m *PageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResult.Merge(m, src)
}
func (m *PageResult) XXX_Size() int {
	return xxx_messageInfo_PageResult.Size(m)
}
func (m *PageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResult.DiscardUnknown(m)
}

var xxx_messageInfo_PageResult proto.InternalMessageInfo

func (m *PageResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PageResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PageResult) GetData() *UserPageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserPageData struct {
	CurrentPage          int32    `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*User  `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPageData) Reset()         { *m = UserPageData{} }
func (m *UserPageData) String() string { return proto.CompactTextString(m) }
func (*UserPageData) ProtoMessage()    {}
func (*UserPageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_46381a6ad9362d17, []int{8}
}

func (m *UserPageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPageData.Unmarshal(m, b)
}
func (m *UserPageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPageData.Marshal(b, m, deterministic)
}
func (m *UserPageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPageData.Merge(m, src)
}
func (m *UserPageData) XXX_Size() int {
	return xxx_messageInfo_UserPageData.Size(m)
}
func (m *UserPageData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPageData.DiscardUnknown(m)
}

var xxx_messageInfo_UserPageData proto.InternalMessageInfo

func (m *UserPageData) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *UserPageData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UserPageData) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("user_proto.DB", DB_name, DB_value)
	proto.RegisterType((*User)(nil), "user_proto.User")
	proto.RegisterType((*Result)(nil), "user_proto.Result")
	proto.RegisterType((*UpdateAndCondition)(nil), "user_proto.UpdateAndCondition")
	proto.RegisterType((*Query)(nil), "user_proto.Query")
	proto.RegisterMapType((map[string]string)(nil), "user_proto.Query.OrderByEntry")
	proto.RegisterType((*PageQuery)(nil), "user_proto.PageQuery")
	proto.RegisterType((*EntityResult)(nil), "user_proto.EntityResult")
	proto.RegisterType((*ListResult)(nil), "user_proto.ListResult")
	proto.RegisterType((*PageResult)(nil), "user_proto.PageResult")
	proto.RegisterType((*UserPageData)(nil), "user_proto.UserPageData")
}

func init() { proto.RegisterFile("user_gen.proto", fileDescriptor_46381a6ad9362d17) }

var fileDescriptor_46381a6ad9362d17 = []byte{
	// 808 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5f, 0x8f, 0xe2, 0x54,
	0x14, 0x07, 0x4a, 0x81, 0x9e, 0x22, 0xcb, 0x5e, 0x75, 0x73, 0x17, 0xcd, 0x04, 0x1b, 0x13, 0x89,
	0xd9, 0xf0, 0xc0, 0xc6, 0xb8, 0xf2, 0x36, 0x0c, 0x8c, 0x4e, 0xa2, 0xbb, 0xd8, 0xd9, 0x8d, 0xc6,
	0x97, 0x7a, 0xa1, 0x77, 0xd8, 0xc6, 0xfe, 0x61, 0xda, 0xdb, 0x75, 0x78, 0xf3, 0x5b, 0xf8, 0x51,
	0x7c, 0xf6, 0x9b, 0x99, 0x73, 0x6e, 0x81, 0x22, 0xec, 0xea, 0xec, 0x53, 0xcf, 0xef, 0xfc, 0xce,
	0xff, 0x73, 0x7a, 0xa1, 0x93, 0x67, 0x32, 0xf5, 0x56, 0x32, 0x1e, 0xae, 0xd3, 0x44, 0x25, 0x0c,
	0x08, 0x93, 0xec, 0xfc, 0x61, 0x40, 0xfd, 0x55, 0x26, 0x53, 0xf6, 0x08, 0x1a, 0xf8, 0xbd, 0xf2,
	0x79, 0xb5, 0x5f, 0x1d, 0x98, 0x6e, 0x81, 0x58, 0x0f, 0x5a, 0x28, 0x3d, 0x17, 0x91, 0xe4, 0xb5,
	0x7e, 0x75, 0x60, 0xb9, 0x3b, 0xcc, 0xba, 0x60, 0xcc, 0x7f, 0xf7, 0xb9, 0x41, 0x6a, 0x14, 0xd1,
	0xda, 0x95, 0x22, 0x24, 0xeb, 0xba, 0xb6, 0xde, 0x62, 0xc6, 0xa1, 0x79, 0xee, 0xfb, 0xa9, 0xcc,
	0x32, 0x6e, 0x12, 0xb5, 0x85, 0xe8, 0x35, 0x09, 0x52, 0xf5, 0xda, 0x17, 0x1b, 0xde, 0xd0, 0x5e,
	0x5b, 0x8c, 0x39, 0xae, 0xe5, 0x1d, 0x6f, 0x52, 0x51, 0x28, 0x62, 0xa5, 0x3f, 0x24, 0x8b, 0x20,
	0x94, 0xbc, 0x45, 0xb6, 0x05, 0x62, 0x7d, 0xb0, 0x5f, 0xdc, 0xdc, 0x04, 0x4b, 0x39, 0x7f, 0x9d,
	0xc4, 0x92, 0x5b, 0x44, 0x96, 0x55, 0xec, 0x53, 0xb0, 0xbe, 0x4b, 0xa2, 0x82, 0x07, 0xe2, 0xf7,
	0x0a, 0xf6, 0x11, 0x98, 0xb3, 0x48, 0x04, 0x21, 0xb7, 0x89, 0xd1, 0x80, 0x9d, 0x01, 0x5c, 0xa4,
	0x52, 0x28, 0xf9, 0x32, 0x88, 0x24, 0x6f, 0x13, 0x55, 0xd2, 0x60, 0x35, 0xd7, 0x4a, 0xa8, 0x3c,
	0xe3, 0x1f, 0xe8, 0xb9, 0x69, 0x84, 0xfa, 0x79, 0x92, 0x5d, 0xf9, 0x19, 0xef, 0xe8, 0x2a, 0x35,
	0xc2, 0x7e, 0x2e, 0xc5, 0x1d, 0x7f, 0xa0, 0x67, 0x76, 0x29, 0xee, 0x9c, 0x09, 0x34, 0x5c, 0x99,
	0xe5, 0xa1, 0x62, 0x0c, 0xea, 0xcb, 0xc4, 0x97, 0xc5, 0x06, 0x48, 0x46, 0xfb, 0x28, 0x5b, 0x15,
	0xa3, 0x47, 0x11, 0xad, 0x7c, 0xa1, 0x44, 0x31, 0x76, 0x92, 0x9d, 0x3f, 0xab, 0xc0, 0x5e, 0xad,
	0x7d, 0xa1, 0xe4, 0x79, 0xec, 0x5f, 0x24, 0xb1, 0x1f, 0xa8, 0x20, 0x89, 0xd9, 0x00, 0x1a, 0x32,
	0x56, 0x81, 0xda, 0x50, 0x48, 0x7b, 0xd4, 0x1d, 0xee, 0x57, 0x3f, 0xc4, 0x35, 0xba, 0x05, 0xcf,
	0xbe, 0x00, 0xf3, 0x36, 0x97, 0xe9, 0x86, 0x12, 0xd9, 0xa3, 0x87, 0x65, 0xc3, 0x1f, 0x91, 0x70,
	0x35, 0xcf, 0x86, 0xf0, 0x61, 0x4e, 0x89, 0x3c, 0x19, 0xad, 0xd5, 0xc6, 0xbb, 0x09, 0x64, 0xe8,
	0x67, 0xdc, 0xe8, 0x1b, 0x03, 0xcb, 0x7d, 0xa8, 0xa9, 0x19, 0x32, 0x97, 0x44, 0x38, 0x7f, 0xd7,
	0xc0, 0xa4, 0x00, 0xec, 0x29, 0xb4, 0x75, 0x32, 0x4f, 0x67, 0x7a, 0x5b, 0x49, 0xb6, 0xb6, 0xd2,
	0x4e, 0x9f, 0x80, 0x95, 0xdd, 0x86, 0xde, 0xbe, 0x36, 0xcb, 0x6d, 0x65, 0xb7, 0xa1, 0x26, 0x9f,
	0x00, 0x23, 0xe2, 0x54, 0x29, 0x5d, 0x62, 0x4a, 0x95, 0xb0, 0x6f, 0xa0, 0x95, 0xa4, 0xbe, 0x4c,
	0xbd, 0xc5, 0x86, 0xd7, 0xfb, 0xc6, 0xc0, 0x1e, 0x9d, 0x1d, 0x75, 0x39, 0x7c, 0x81, 0x16, 0x93,
	0xcd, 0x2c, 0x56, 0xe9, 0xc6, 0x6d, 0x26, 0x1a, 0xb1, 0x33, 0xa8, 0xf9, 0x0b, 0xba, 0xda, 0xce,
	0xa8, 0x53, 0x76, 0x9a, 0x4e, 0xdc, 0x9a, 0xbf, 0x60, 0x9f, 0x41, 0x3b, 0x93, 0xa1, 0x5c, 0x2a,
	0x5d, 0x43, 0x71, 0xc4, 0xb6, 0xd6, 0x51, 0xfa, 0xde, 0x18, 0xda, 0xe5, 0xd8, 0xb8, 0xd7, 0xdf,
	0xa4, 0x1e, 0x82, 0xe5, 0xa2, 0x88, 0xf7, 0xf7, 0x46, 0x84, 0xf9, 0xf6, 0x37, 0xd3, 0x60, 0x5c,
	0x7b, 0x56, 0x75, 0x96, 0x60, 0xcd, 0xc5, 0x4a, 0xea, 0xa6, 0x77, 0x9b, 0xaa, 0xfe, 0xc7, 0xa6,
	0x18, 0xd4, 0xd7, 0x62, 0xa5, 0xc3, 0x99, 0x2e, 0xc9, 0xec, 0x31, 0xb4, 0xf0, 0xeb, 0xc5, 0x79,
	0x44, 0xf7, 0x63, 0xba, 0x4d, 0xc4, 0xcf, 0xf3, 0xc8, 0xf9, 0x05, 0xda, 0x33, 0x1a, 0xfc, 0xbd,
	0x8e, 0xf1, 0xf3, 0xd2, 0x31, 0x9e, 0x5a, 0xa6, 0x3e, 0xcf, 0x9f, 0x01, 0xbe, 0x0f, 0x32, 0xf5,
	0x9e, 0x91, 0x8d, 0x77, 0x44, 0xfe, 0x15, 0x00, 0x47, 0x73, 0xaf, 0xc8, 0x4f, 0x0e, 0x6a, 0xe6,
	0xff, 0x8e, 0x8c, 0xf1, 0xa6, 0x42, 0x89, 0x22, 0x43, 0x04, 0xed, 0xb2, 0x16, 0x77, 0xbd, 0xcc,
	0xd3, 0x54, 0xc6, 0xca, 0xa3, 0xf1, 0xea, 0x5c, 0x76, 0xa1, 0x43, 0x33, 0xdc, 0xe4, 0x32, 0xc9,
	0x63, 0x55, 0x8c, 0x5e, 0x03, 0x6c, 0x28, 0x0c, 0x32, 0xf5, 0xf6, 0x86, 0x90, 0xfd, 0xf2, 0x31,
	0xd4, 0xa6, 0x13, 0xd6, 0x82, 0xba, 0x3b, 0x3b, 0x9f, 0x76, 0x2b, 0xcc, 0x02, 0xf3, 0x27, 0xf7,
	0xea, 0xe5, 0xac, 0x5b, 0x1d, 0xfd, 0x65, 0x80, 0x8d, 0x96, 0xd7, 0x32, 0x7d, 0x13, 0x2c, 0x25,
	0x1b, 0x6f, 0x9f, 0x26, 0x7a, 0xc0, 0x8f, 0x02, 0xf6, 0x0e, 0x3a, 0x2b, 0xef, 0xd6, 0xa9, 0xb0,
	0x09, 0x80, 0x7e, 0x2f, 0xc8, 0xf7, 0xe0, 0x47, 0x38, 0x7e, 0x47, 0x7a, 0xac, 0xcc, 0xef, 0x62,
	0x3c, 0x83, 0xe6, 0xb7, 0x52, 0x51, 0x80, 0xe3, 0x2b, 0x7c, 0x67, 0xf6, 0x31, 0xd8, 0x85, 0x27,
	0x9e, 0xc5, 0x29, 0xef, 0x47, 0x65, 0xd5, 0xfe, 0x76, 0x9c, 0x0a, 0xfb, 0x0a, 0x60, 0x2a, 0x43,
	0x59, 0x54, 0x7e, 0xc2, 0xf5, 0x74, 0xb1, 0x13, 0x78, 0x50, 0xa4, 0xc4, 0x15, 0x51, 0xda, 0x8f,
	0xcb, 0x86, 0xbb, 0x1f, 0xec, 0x30, 0xf5, 0xfe, 0xb8, 0x9c, 0x0a, 0xfb, 0x1a, 0xda, 0x45, 0x8c,
	0x0b, 0xda, 0xe8, 0xff, 0x4d, 0xbe, 0x68, 0x10, 0x7e, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0x64, 0x4f, 0x92, 0x8a, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	//创建
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明，如果要更新的是默认值 请使用update_empty_fields 大写字段数组
	UpdateUser(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUser(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUserList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	DeleteUser(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUserPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUserCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error) {
	out := new(ListResult)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/GetUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error) {
	out := new(PageResult)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/GetUserPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/GetUserCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	//创建
	CreateUser(context.Context, *User) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明，如果要更新的是默认值 请使用update_empty_fields 大写字段数组
	UpdateUser(context.Context, *UpdateAndCondition) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUser(context.Context, *Query) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUserList(context.Context, *Query) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	DeleteUser(context.Context, *Query) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUserPageList(context.Context, *PageQuery) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetUserCount(context.Context, *Query) (*Result, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *User) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateAndCondition) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *Query) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserList(ctx context.Context, req *Query) (*ListResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserPageList(ctx context.Context, req *PageQuery) (*PageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPageList not implemented")
}
func (*UnimplementedUserServiceServer) GetUserCount(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCount not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCondition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateAndCondition))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserList(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/GetUserPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserPageList(ctx, req.(*PageQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/GetUserCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserCount(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _UserService_GetUserList_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUserPageList",
			Handler:    _UserService_GetUserPageList_Handler,
		},
		{
			MethodName: "GetUserCount",
			Handler:    _UserService_GetUserCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_gen.proto",
}
