// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hys_city_gen.proto

package hys_city_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//主从库
type DB int32

const (
	//读库
	DB_READ DB = 0
	//写库
	DB_WRITE DB = 1
)

var DB_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}

var DB_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x DB) String() string {
	return proto.EnumName(DB_name, int32(x))
}

func (DB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{0}
}

type HysCity struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parentid             int32    `protobuf:"varint,2,opt,name=parentid,proto3" json:"parentid,omitempty"`
	Cityname             string   `protobuf:"bytes,3,opt,name=cityname,proto3" json:"cityname,omitempty"`
	Regiontype           int32    `protobuf:"varint,4,opt,name=regiontype,proto3" json:"regiontype,omitempty"`
	Agencyid             int32    `protobuf:"varint,5,opt,name=agencyid,proto3" json:"agencyid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HysCity) Reset()         { *m = HysCity{} }
func (m *HysCity) String() string { return proto.CompactTextString(m) }
func (*HysCity) ProtoMessage()    {}
func (*HysCity) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{0}
}

func (m *HysCity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HysCity.Unmarshal(m, b)
}
func (m *HysCity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HysCity.Marshal(b, m, deterministic)
}
func (m *HysCity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HysCity.Merge(m, src)
}
func (m *HysCity) XXX_Size() int {
	return xxx_messageInfo_HysCity.Size(m)
}
func (m *HysCity) XXX_DiscardUnknown() {
	xxx_messageInfo_HysCity.DiscardUnknown(m)
}

var xxx_messageInfo_HysCity proto.InternalMessageInfo

func (m *HysCity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HysCity) GetParentid() int32 {
	if m != nil {
		return m.Parentid
	}
	return 0
}

func (m *HysCity) GetCityname() string {
	if m != nil {
		return m.Cityname
	}
	return ""
}

func (m *HysCity) GetRegiontype() int32 {
	if m != nil {
		return m.Regiontype
	}
	return 0
}

func (m *HysCity) GetAgencyid() int32 {
	if m != nil {
		return m.Agencyid
	}
	return 0
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 按条件更新数据
type UpdateAndCondition struct {
	// 更新数据，如果filed对应为空值，则需要在 update_empty_fields 中声明
	Entity *HysCity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	//查询条件
	Query *Query `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 需要赋空值的字段 大写字段数组
	UpdateEmptyFields    []string `protobuf:"bytes,3,rep,name=update_empty_fields,json=updateEmptyFields,proto3" json:"update_empty_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAndCondition) Reset()         { *m = UpdateAndCondition{} }
func (m *UpdateAndCondition) String() string { return proto.CompactTextString(m) }
func (*UpdateAndCondition) ProtoMessage()    {}
func (*UpdateAndCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{2}
}

func (m *UpdateAndCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAndCondition.Unmarshal(m, b)
}
func (m *UpdateAndCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAndCondition.Marshal(b, m, deterministic)
}
func (m *UpdateAndCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAndCondition.Merge(m, src)
}
func (m *UpdateAndCondition) XXX_Size() int {
	return xxx_messageInfo_UpdateAndCondition.Size(m)
}
func (m *UpdateAndCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAndCondition.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAndCondition proto.InternalMessageInfo

func (m *UpdateAndCondition) GetEntity() *HysCity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *UpdateAndCondition) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *UpdateAndCondition) GetUpdateEmptyFields() []string {
	if m != nil {
		return m.UpdateEmptyFields
	}
	return nil
}

//按条件查询
type Query struct {
	// 按照实体查询 （和sql查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	EntityQuery *HysCity `protobuf:"bytes,1,opt,name=entity_query,json=entityQuery,proto3" json:"entity_query,omitempty"`
	// 按照sql查询（和实体查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// "id=1 and status in(3,4) and createtime >'2018' "
	SqlQuery string `protobuf:"bytes,2,opt,name=sql_query,json=sqlQuery,proto3" json:"sql_query,omitempty"`
	// 用空值当检索条件的字段 大写字段数组
	QueryEmptyFields []string `protobuf:"bytes,3,rep,name=query_empty_fields,json=queryEmptyFields,proto3" json:"query_empty_fields,omitempty"`
	//排序条件 key值为数据库字段 ["id":"desc","create_time":asc"]
	OrderBy map[string]string `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//是否查询主库，默认不读取 DB.READ
	Db DB `protobuf:"varint,5,opt,name=db,proto3,enum=hys_city_proto.DB" json:"db,omitempty"`
	//制定select查询的字段，如 "id,username,age"
	SelectField          string   `protobuf:"bytes,6,opt,name=select_field,json=selectField,proto3" json:"select_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{3}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetEntityQuery() *HysCity {
	if m != nil {
		return m.EntityQuery
	}
	return nil
}

func (m *Query) GetSqlQuery() string {
	if m != nil {
		return m.SqlQuery
	}
	return ""
}

func (m *Query) GetQueryEmptyFields() []string {
	if m != nil {
		return m.QueryEmptyFields
	}
	return nil
}

func (m *Query) GetOrderBy() map[string]string {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *Query) GetDb() DB {
	if m != nil {
		return m.Db
	}
	return DB_READ
}

func (m *Query) GetSelectField() string {
	if m != nil {
		return m.SelectField
	}
	return ""
}

//分页查询
type PageQuery struct {
	//查询条件
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{4}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *PageQuery) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageQuery) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type EntityResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *HysCity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityResult) Reset()         { *m = EntityResult{} }
func (m *EntityResult) String() string { return proto.CompactTextString(m) }
func (*EntityResult) ProtoMessage()    {}
func (*EntityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{5}
}

func (m *EntityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityResult.Unmarshal(m, b)
}
func (m *EntityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityResult.Marshal(b, m, deterministic)
}
func (m *EntityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityResult.Merge(m, src)
}
func (m *EntityResult) XXX_Size() int {
	return xxx_messageInfo_EntityResult.Size(m)
}
func (m *EntityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityResult.DiscardUnknown(m)
}

var xxx_messageInfo_EntityResult proto.InternalMessageInfo

func (m *EntityResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EntityResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EntityResult) GetData() *HysCity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResult struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*HysCity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResult) Reset()         { *m = ListResult{} }
func (m *ListResult) String() string { return proto.CompactTextString(m) }
func (*ListResult) ProtoMessage()    {}
func (*ListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{6}
}

func (m *ListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResult.Unmarshal(m, b)
}
func (m *ListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResult.Marshal(b, m, deterministic)
}
func (m *ListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResult.Merge(m, src)
}
func (m *ListResult) XXX_Size() int {
	return xxx_messageInfo_ListResult.Size(m)
}
func (m *ListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListResult proto.InternalMessageInfo

func (m *ListResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResult) GetData() []*HysCity {
	if m != nil {
		return m.Data
	}
	return nil
}

type PageResult struct {
	Code                 int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *HysCityPageData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PageResult) Reset()         { *m = PageResult{} }
func (m *PageResult) String() string { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()    {}
func (*PageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{7}
}

func (m *PageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResult.Unmarshal(m, b)
}
func (m *PageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResult.Marshal(b, m, deterministic)
}
func (m *PageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResult.Merge(m, src)
}
func (m *PageResult) XXX_Size() int {
	return xxx_messageInfo_PageResult.Size(m)
}
func (m *PageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResult.DiscardUnknown(m)
}

var xxx_messageInfo_PageResult proto.InternalMessageInfo

func (m *PageResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PageResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PageResult) GetData() *HysCityPageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type HysCityPageData struct {
	CurrentPage          int32      `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Count                int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*HysCity `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HysCityPageData) Reset()         { *m = HysCityPageData{} }
func (m *HysCityPageData) String() string { return proto.CompactTextString(m) }
func (*HysCityPageData) ProtoMessage()    {}
func (*HysCityPageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d44d69476b08a9, []int{8}
}

func (m *HysCityPageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HysCityPageData.Unmarshal(m, b)
}
func (m *HysCityPageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HysCityPageData.Marshal(b, m, deterministic)
}
func (m *HysCityPageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HysCityPageData.Merge(m, src)
}
func (m *HysCityPageData) XXX_Size() int {
	return xxx_messageInfo_HysCityPageData.Size(m)
}
func (m *HysCityPageData) XXX_DiscardUnknown() {
	xxx_messageInfo_HysCityPageData.DiscardUnknown(m)
}

var xxx_messageInfo_HysCityPageData proto.InternalMessageInfo

func (m *HysCityPageData) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *HysCityPageData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HysCityPageData) GetList() []*HysCity {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("hys_city_proto.DB", DB_name, DB_value)
	proto.RegisterType((*HysCity)(nil), "hys_city_proto.HysCity")
	proto.RegisterType((*Result)(nil), "hys_city_proto.Result")
	proto.RegisterType((*UpdateAndCondition)(nil), "hys_city_proto.UpdateAndCondition")
	proto.RegisterType((*Query)(nil), "hys_city_proto.Query")
	proto.RegisterMapType((map[string]string)(nil), "hys_city_proto.Query.OrderByEntry")
	proto.RegisterType((*PageQuery)(nil), "hys_city_proto.PageQuery")
	proto.RegisterType((*EntityResult)(nil), "hys_city_proto.EntityResult")
	proto.RegisterType((*ListResult)(nil), "hys_city_proto.ListResult")
	proto.RegisterType((*PageResult)(nil), "hys_city_proto.PageResult")
	proto.RegisterType((*HysCityPageData)(nil), "hys_city_proto.HysCityPageData")
}

func init() { proto.RegisterFile("hys_city_gen.proto", fileDescriptor_28d44d69476b08a9) }

var fileDescriptor_28d44d69476b08a9 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x9d, 0x43, 0xe3, 0x49, 0x9a, 0xa6, 0xd3, 0xff, 0xe0, 0x06, 0x04, 0xc1, 0x57, 0x11,
	0x45, 0xa9, 0x94, 0xde, 0xa0, 0x22, 0x24, 0x9a, 0x03, 0x14, 0x89, 0x72, 0x58, 0x40, 0x48, 0xdc,
	0x58, 0x8e, 0xbd, 0x18, 0x0b, 0xc7, 0x4e, 0xed, 0x75, 0x91, 0x5f, 0x01, 0x89, 0x97, 0xe0, 0x89,
	0x78, 0x24, 0xb4, 0xbb, 0x4e, 0x9c, 0xba, 0x0d, 0xa1, 0x5c, 0x79, 0x67, 0xe7, 0xdb, 0x6f, 0xbe,
	0xd9, 0xf9, 0xbc, 0x80, 0x9f, 0xd3, 0xd8, 0xb4, 0x3d, 0x96, 0x9a, 0x2e, 0x0d, 0xfa, 0xf3, 0x28,
	0x64, 0x21, 0xb6, 0x96, 0x7b, 0x22, 0x36, 0xbe, 0x2b, 0xb0, 0x75, 0x9a, 0xc6, 0x23, 0x8f, 0xa5,
	0xd8, 0x02, 0xd5, 0x73, 0x74, 0xa5, 0xab, 0xf4, 0xaa, 0x44, 0xf5, 0x1c, 0xec, 0x40, 0x7d, 0x6e,
	0x45, 0x34, 0x60, 0x9e, 0xa3, 0xab, 0x62, 0x77, 0x19, 0xf3, 0x1c, 0x67, 0x09, 0xac, 0x19, 0xd5,
	0xcb, 0x5d, 0xa5, 0xa7, 0x91, 0x65, 0x8c, 0x77, 0x00, 0x22, 0xea, 0x7a, 0x61, 0xc0, 0xd2, 0x39,
	0xd5, 0x2b, 0xe2, 0xe4, 0xca, 0x0e, 0x3f, 0x6b, 0xb9, 0x34, 0xb0, 0x53, 0xcf, 0xd1, 0xab, 0x92,
	0x77, 0x11, 0x1b, 0x43, 0xa8, 0x11, 0x1a, 0x27, 0x3e, 0x43, 0x84, 0x8a, 0x1d, 0x3a, 0x34, 0xd3,
	0x23, 0xd6, 0xd8, 0x86, 0xf2, 0x2c, 0x76, 0x85, 0x18, 0x8d, 0xf0, 0x25, 0x47, 0x39, 0x16, 0xb3,
	0x32, 0x0d, 0x62, 0x6d, 0xfc, 0x50, 0x00, 0xdf, 0xcf, 0x1d, 0x8b, 0xd1, 0x93, 0xc0, 0x19, 0x85,
	0x81, 0xe3, 0x31, 0x2f, 0x0c, 0xf0, 0x10, 0x6a, 0x5c, 0x3b, 0x4b, 0x05, 0x65, 0x63, 0xf0, 0x7f,
	0xff, 0xf2, 0x5d, 0xf4, 0xb3, 0x7b, 0x20, 0x19, 0x0c, 0x0f, 0xa0, 0x7a, 0x9e, 0xd0, 0x28, 0x15,
	0xf5, 0x1a, 0x83, 0x7f, 0x8b, 0xf8, 0x37, 0x3c, 0x49, 0x24, 0x06, 0xfb, 0xb0, 0x97, 0x88, 0x9a,
	0x26, 0x9d, 0xcd, 0x59, 0x6a, 0x7e, 0xf2, 0xa8, 0xef, 0xc4, 0x7a, 0xb9, 0x5b, 0xee, 0x69, 0x64,
	0x57, 0xa6, 0x26, 0x3c, 0xf3, 0x54, 0x24, 0x8c, 0x9f, 0x2a, 0x54, 0x05, 0x01, 0x1e, 0x43, 0x53,
	0x16, 0x34, 0x65, 0xb5, 0x0d, 0xea, 0x1a, 0x12, 0x2c, 0xcf, 0xde, 0x02, 0x2d, 0x3e, 0xf7, 0xcd,
	0x5c, 0xa6, 0x46, 0xea, 0xf1, 0xb9, 0x2f, 0x93, 0x0f, 0x00, 0x45, 0xe2, 0x3a, 0x45, 0x6d, 0x91,
	0x59, 0x11, 0x84, 0x8f, 0xa1, 0x1e, 0x46, 0x0e, 0x8d, 0xcc, 0x69, 0xaa, 0x57, 0xba, 0xe5, 0x5e,
	0x63, 0x60, 0x5c, 0xdb, 0x70, 0xff, 0x15, 0x47, 0x0d, 0xd3, 0x49, 0xc0, 0xa2, 0x94, 0x6c, 0x85,
	0x32, 0x42, 0x03, 0x54, 0x67, 0x2a, 0xc6, 0xd9, 0x1a, 0x60, 0xf1, 0xe0, 0x78, 0x48, 0x54, 0x67,
	0x8a, 0xf7, 0xa0, 0x19, 0x53, 0x9f, 0xda, 0x4c, 0x6a, 0xd1, 0x6b, 0x42, 0x70, 0x43, 0xee, 0x09,
	0x19, 0x9d, 0x63, 0x68, 0xae, 0xf2, 0xf3, 0x89, 0x7f, 0xa1, 0xf2, 0x4e, 0x34, 0xc2, 0x97, 0xf8,
	0x0f, 0x54, 0x2f, 0x2c, 0x3f, 0xa1, 0x59, 0xbb, 0x32, 0x38, 0x56, 0x1f, 0x2a, 0x86, 0x0b, 0xda,
	0x6b, 0xcb, 0xa5, 0xb2, 0xf9, 0xe5, 0xf0, 0x94, 0x3f, 0x18, 0x1e, 0x42, 0x65, 0x6e, 0xb9, 0x34,
	0x73, 0xb9, 0x58, 0xe3, 0x3e, 0x77, 0xbf, 0x4b, 0xcd, 0x20, 0x99, 0x09, 0x77, 0x55, 0xc9, 0x16,
	0x8f, 0x5f, 0x26, 0x33, 0xc3, 0x82, 0xe6, 0x44, 0x0c, 0xe1, 0x46, 0x56, 0x3d, 0x58, 0xb1, 0xea,
	0x6f, 0xe6, 0x2b, 0x3d, 0x6c, 0x02, 0xbc, 0xf0, 0x62, 0xf6, 0x97, 0x05, 0xca, 0x9b, 0x0b, 0xb8,
	0x00, 0xfc, 0xb2, 0x6e, 0x54, 0xe0, 0xe8, 0x52, 0x07, 0x77, 0xd7, 0x14, 0xe0, 0xb4, 0x63, 0x8b,
	0x59, 0x59, 0xa1, 0xaf, 0xb0, 0x53, 0x48, 0x70, 0x1f, 0xd8, 0x49, 0xc4, 0x5f, 0x12, 0x53, 0x5c,
	0xbb, 0xac, 0xda, 0xc8, 0xf6, 0x38, 0x8c, 0x4f, 0xd9, 0x0e, 0x93, 0x80, 0x65, 0x23, 0x91, 0x01,
	0xef, 0xd0, 0xf7, 0x62, 0xb6, 0xb1, 0x43, 0x0e, 0xba, 0xbf, 0x0f, 0xea, 0x78, 0x88, 0x75, 0xa8,
	0x90, 0xc9, 0xc9, 0xb8, 0x5d, 0x42, 0x0d, 0xaa, 0x1f, 0xc8, 0xf3, 0x77, 0x93, 0xb6, 0x32, 0xf8,
	0x56, 0x81, 0x56, 0x06, 0x7e, 0x4b, 0xa3, 0x0b, 0xcf, 0xa6, 0x78, 0x0a, 0xdb, 0xa3, 0x88, 0x5a,
	0x8c, 0x2e, 0x5e, 0xc3, 0x75, 0xec, 0x9d, 0xdb, 0xc5, 0xc4, 0xaa, 0x17, 0x8c, 0x12, 0x9e, 0xc1,
	0xb6, 0x7c, 0x7d, 0x16, 0x4c, 0x57, 0xfe, 0xa3, 0xab, 0x8f, 0x53, 0xe7, 0xbf, 0x22, 0x66, 0x49,
	0x37, 0x02, 0x78, 0x46, 0xd9, 0x82, 0xeb, 0x7a, 0x1f, 0x6f, 0xd4, 0x34, 0x81, 0x56, 0x4e, 0xc2,
	0x8d, 0xb5, 0x8e, 0xa8, 0x53, 0xdc, 0xce, 0x5d, 0x68, 0x94, 0xf0, 0x09, 0x6c, 0x8f, 0xa9, 0x4f,
	0xf3, 0xd6, 0xd6, 0xb0, 0xac, 0xef, 0xe6, 0x0c, 0x30, 0x17, 0xc2, 0x27, 0x2d, 0xc4, 0xec, 0x17,
	0xf1, 0xcb, 0xff, 0xf8, 0xaa, 0xa0, 0xdc, 0xb5, 0x46, 0x09, 0x87, 0xb0, 0x93, 0xd3, 0x8d, 0x84,
	0x47, 0x6e, 0x2a, 0x69, 0xb8, 0xf7, 0x71, 0xb7, 0x7f, 0xf8, 0xe8, 0x72, 0x76, 0x5a, 0x13, 0x9f,
	0xa3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x1c, 0x90, 0x58, 0x44, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HysCityServiceClient is the client API for HysCityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HysCityServiceClient interface {
	//创建
	CreateHysCity(ctx context.Context, in *HysCity, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明，如果要更新的是默认值 请使用update_empty_fields 大写字段数组
	UpdateHysCity(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCity(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCityList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	DeleteHysCity(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCityPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCityCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
}

type hysCityServiceClient struct {
	cc *grpc.ClientConn
}

func NewHysCityServiceClient(cc *grpc.ClientConn) HysCityServiceClient {
	return &hysCityServiceClient{cc}
}

func (c *hysCityServiceClient) CreateHysCity(ctx context.Context, in *HysCity, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/CreateHysCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hysCityServiceClient) UpdateHysCity(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/UpdateHysCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hysCityServiceClient) GetHysCity(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/GetHysCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hysCityServiceClient) GetHysCityList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error) {
	out := new(ListResult)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/GetHysCityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hysCityServiceClient) DeleteHysCity(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/DeleteHysCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hysCityServiceClient) GetHysCityPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error) {
	out := new(PageResult)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/GetHysCityPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hysCityServiceClient) GetHysCityCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/hys_city_proto.HysCityService/GetHysCityCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HysCityServiceServer is the server API for HysCityService service.
type HysCityServiceServer interface {
	//创建
	CreateHysCity(context.Context, *HysCity) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明，如果要更新的是默认值 请使用update_empty_fields 大写字段数组
	UpdateHysCity(context.Context, *UpdateAndCondition) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCity(context.Context, *Query) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCityList(context.Context, *Query) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	DeleteHysCity(context.Context, *Query) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCityPageList(context.Context, *PageQuery) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetHysCityCount(context.Context, *Query) (*Result, error)
}

// UnimplementedHysCityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHysCityServiceServer struct {
}

func (*UnimplementedHysCityServiceServer) CreateHysCity(ctx context.Context, req *HysCity) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHysCity not implemented")
}
func (*UnimplementedHysCityServiceServer) UpdateHysCity(ctx context.Context, req *UpdateAndCondition) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHysCity not implemented")
}
func (*UnimplementedHysCityServiceServer) GetHysCity(ctx context.Context, req *Query) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHysCity not implemented")
}
func (*UnimplementedHysCityServiceServer) GetHysCityList(ctx context.Context, req *Query) (*ListResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHysCityList not implemented")
}
func (*UnimplementedHysCityServiceServer) DeleteHysCity(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHysCity not implemented")
}
func (*UnimplementedHysCityServiceServer) GetHysCityPageList(ctx context.Context, req *PageQuery) (*PageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHysCityPageList not implemented")
}
func (*UnimplementedHysCityServiceServer) GetHysCityCount(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHysCityCount not implemented")
}

func RegisterHysCityServiceServer(s *grpc.Server, srv HysCityServiceServer) {
	s.RegisterService(&_HysCityService_serviceDesc, srv)
}

func _HysCityService_CreateHysCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HysCity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).CreateHysCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/CreateHysCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).CreateHysCity(ctx, req.(*HysCity))
	}
	return interceptor(ctx, in, info, handler)
}

func _HysCityService_UpdateHysCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCondition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).UpdateHysCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/UpdateHysCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).UpdateHysCity(ctx, req.(*UpdateAndCondition))
	}
	return interceptor(ctx, in, info, handler)
}

func _HysCityService_GetHysCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).GetHysCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/GetHysCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).GetHysCity(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _HysCityService_GetHysCityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).GetHysCityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/GetHysCityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).GetHysCityList(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _HysCityService_DeleteHysCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).DeleteHysCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/DeleteHysCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).DeleteHysCity(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _HysCityService_GetHysCityPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).GetHysCityPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/GetHysCityPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).GetHysCityPageList(ctx, req.(*PageQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _HysCityService_GetHysCityCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HysCityServiceServer).GetHysCityCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hys_city_proto.HysCityService/GetHysCityCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HysCityServiceServer).GetHysCityCount(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _HysCityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hys_city_proto.HysCityService",
	HandlerType: (*HysCityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHysCity",
			Handler:    _HysCityService_CreateHysCity_Handler,
		},
		{
			MethodName: "UpdateHysCity",
			Handler:    _HysCityService_UpdateHysCity_Handler,
		},
		{
			MethodName: "GetHysCity",
			Handler:    _HysCityService_GetHysCity_Handler,
		},
		{
			MethodName: "GetHysCityList",
			Handler:    _HysCityService_GetHysCityList_Handler,
		},
		{
			MethodName: "DeleteHysCity",
			Handler:    _HysCityService_DeleteHysCity_Handler,
		},
		{
			MethodName: "GetHysCityPageList",
			Handler:    _HysCityService_GetHysCityPageList_Handler,
		},
		{
			MethodName: "GetHysCityCount",
			Handler:    _HysCityService_GetHysCityCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hys_city_gen.proto",
}
