// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sq_user_blacklist_gen.proto

package sq_user_blacklist_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//主从库
type DB int32

const (
	//读库
	DB_READ DB = 0
	//写库
	DB_WRITE DB = 1
)

var DB_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}

var DB_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x DB) String() string {
	return proto.EnumName(DB_name, int32(x))
}

func (DB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{0}
}

type SqUserBlacklist struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid               int32    `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Createtime           string   `protobuf:"bytes,4,opt,name=createtime,proto3" json:"createtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqUserBlacklist) Reset()         { *m = SqUserBlacklist{} }
func (m *SqUserBlacklist) String() string { return proto.CompactTextString(m) }
func (*SqUserBlacklist) ProtoMessage()    {}
func (*SqUserBlacklist) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{0}
}

func (m *SqUserBlacklist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqUserBlacklist.Unmarshal(m, b)
}
func (m *SqUserBlacklist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqUserBlacklist.Marshal(b, m, deterministic)
}
func (m *SqUserBlacklist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqUserBlacklist.Merge(m, src)
}
func (m *SqUserBlacklist) XXX_Size() int {
	return xxx_messageInfo_SqUserBlacklist.Size(m)
}
func (m *SqUserBlacklist) XXX_DiscardUnknown() {
	xxx_messageInfo_SqUserBlacklist.DiscardUnknown(m)
}

var xxx_messageInfo_SqUserBlacklist proto.InternalMessageInfo

func (m *SqUserBlacklist) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SqUserBlacklist) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *SqUserBlacklist) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SqUserBlacklist) GetCreatetime() string {
	if m != nil {
		return m.Createtime
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 按条件更新数据
type UpdateAndCondition struct {
	// 更新数据，如果filed对应为空值，则需要在 update_empty_fields 中声明
	Entity *SqUserBlacklist `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	//查询条件
	Query *Query `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 需要赋空值的字段 大写字段数组
	UpdateEmptyFields    []string `protobuf:"bytes,3,rep,name=update_empty_fields,json=updateEmptyFields,proto3" json:"update_empty_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAndCondition) Reset()         { *m = UpdateAndCondition{} }
func (m *UpdateAndCondition) String() string { return proto.CompactTextString(m) }
func (*UpdateAndCondition) ProtoMessage()    {}
func (*UpdateAndCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{2}
}

func (m *UpdateAndCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAndCondition.Unmarshal(m, b)
}
func (m *UpdateAndCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAndCondition.Marshal(b, m, deterministic)
}
func (m *UpdateAndCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAndCondition.Merge(m, src)
}
func (m *UpdateAndCondition) XXX_Size() int {
	return xxx_messageInfo_UpdateAndCondition.Size(m)
}
func (m *UpdateAndCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAndCondition.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAndCondition proto.InternalMessageInfo

func (m *UpdateAndCondition) GetEntity() *SqUserBlacklist {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *UpdateAndCondition) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *UpdateAndCondition) GetUpdateEmptyFields() []string {
	if m != nil {
		return m.UpdateEmptyFields
	}
	return nil
}

//按条件查询
type Query struct {
	// 按照实体查询 （和sql查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	EntityQuery *SqUserBlacklist `protobuf:"bytes,1,opt,name=entity_query,json=entityQuery,proto3" json:"entity_query,omitempty"`
	// 按照sql查询（和实体查询二选一，sql查询优先使用），如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// "id=1 and status in(3,4) and createtime >'2018' "
	SqlQuery string `protobuf:"bytes,2,opt,name=sql_query,json=sqlQuery,proto3" json:"sql_query,omitempty"`
	// 用空值当检索条件的字段 大写字段数组
	QueryEmptyFields []string `protobuf:"bytes,3,rep,name=query_empty_fields,json=queryEmptyFields,proto3" json:"query_empty_fields,omitempty"`
	//排序条件 key值为数据库字段 ["id":"desc","create_time":asc"]
	OrderBy map[string]string `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//是否查询主库，默认不读取 DB.READ
	Db DB `protobuf:"varint,5,opt,name=db,proto3,enum=sq_user_blacklist_proto.DB" json:"db,omitempty"`
	//制定select查询的字段，如 "id,username,age"
	SelectField          string   `protobuf:"bytes,6,opt,name=select_field,json=selectField,proto3" json:"select_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{3}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetEntityQuery() *SqUserBlacklist {
	if m != nil {
		return m.EntityQuery
	}
	return nil
}

func (m *Query) GetSqlQuery() string {
	if m != nil {
		return m.SqlQuery
	}
	return ""
}

func (m *Query) GetQueryEmptyFields() []string {
	if m != nil {
		return m.QueryEmptyFields
	}
	return nil
}

func (m *Query) GetOrderBy() map[string]string {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *Query) GetDb() DB {
	if m != nil {
		return m.Db
	}
	return DB_READ
}

func (m *Query) GetSelectField() string {
	if m != nil {
		return m.SelectField
	}
	return ""
}

//分页查询
type PageQuery struct {
	//查询条件
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{4}
}

func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *PageQuery) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageQuery) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type EntityResult struct {
	Code                 int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *SqUserBlacklist `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EntityResult) Reset()         { *m = EntityResult{} }
func (m *EntityResult) String() string { return proto.CompactTextString(m) }
func (*EntityResult) ProtoMessage()    {}
func (*EntityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{5}
}

func (m *EntityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityResult.Unmarshal(m, b)
}
func (m *EntityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityResult.Marshal(b, m, deterministic)
}
func (m *EntityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityResult.Merge(m, src)
}
func (m *EntityResult) XXX_Size() int {
	return xxx_messageInfo_EntityResult.Size(m)
}
func (m *EntityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityResult.DiscardUnknown(m)
}

var xxx_messageInfo_EntityResult proto.InternalMessageInfo

func (m *EntityResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EntityResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EntityResult) GetData() *SqUserBlacklist {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResult struct {
	Code                 int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*SqUserBlacklist `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListResult) Reset()         { *m = ListResult{} }
func (m *ListResult) String() string { return proto.CompactTextString(m) }
func (*ListResult) ProtoMessage()    {}
func (*ListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{6}
}

func (m *ListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResult.Unmarshal(m, b)
}
func (m *ListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResult.Marshal(b, m, deterministic)
}
func (m *ListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResult.Merge(m, src)
}
func (m *ListResult) XXX_Size() int {
	return xxx_messageInfo_ListResult.Size(m)
}
func (m *ListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListResult proto.InternalMessageInfo

func (m *ListResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResult) GetData() []*SqUserBlacklist {
	if m != nil {
		return m.Data
	}
	return nil
}

type PageResult struct {
	Code                 int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *SqUserBlacklistPageData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PageResult) Reset()         { *m = PageResult{} }
func (m *PageResult) String() string { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()    {}
func (*PageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{7}
}

func (m *PageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResult.Unmarshal(m, b)
}
func (m *PageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResult.Marshal(b, m, deterministic)
}
func (m *PageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResult.Merge(m, src)
}
func (m *PageResult) XXX_Size() int {
	return xxx_messageInfo_PageResult.Size(m)
}
func (m *PageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResult.DiscardUnknown(m)
}

var xxx_messageInfo_PageResult proto.InternalMessageInfo

func (m *PageResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PageResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PageResult) GetData() *SqUserBlacklistPageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SqUserBlacklistPageData struct {
	CurrentPage          int32              `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Count                int32              `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*SqUserBlacklist `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SqUserBlacklistPageData) Reset()         { *m = SqUserBlacklistPageData{} }
func (m *SqUserBlacklistPageData) String() string { return proto.CompactTextString(m) }
func (*SqUserBlacklistPageData) ProtoMessage()    {}
func (*SqUserBlacklistPageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6beab68822faa327, []int{8}
}

func (m *SqUserBlacklistPageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqUserBlacklistPageData.Unmarshal(m, b)
}
func (m *SqUserBlacklistPageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqUserBlacklistPageData.Marshal(b, m, deterministic)
}
func (m *SqUserBlacklistPageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqUserBlacklistPageData.Merge(m, src)
}
func (m *SqUserBlacklistPageData) XXX_Size() int {
	return xxx_messageInfo_SqUserBlacklistPageData.Size(m)
}
func (m *SqUserBlacklistPageData) XXX_DiscardUnknown() {
	xxx_messageInfo_SqUserBlacklistPageData.DiscardUnknown(m)
}

var xxx_messageInfo_SqUserBlacklistPageData proto.InternalMessageInfo

func (m *SqUserBlacklistPageData) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *SqUserBlacklistPageData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SqUserBlacklistPageData) GetList() []*SqUserBlacklist {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("sq_user_blacklist_proto.DB", DB_name, DB_value)
	proto.RegisterType((*SqUserBlacklist)(nil), "sq_user_blacklist_proto.SqUserBlacklist")
	proto.RegisterType((*Result)(nil), "sq_user_blacklist_proto.Result")
	proto.RegisterType((*UpdateAndCondition)(nil), "sq_user_blacklist_proto.UpdateAndCondition")
	proto.RegisterType((*Query)(nil), "sq_user_blacklist_proto.Query")
	proto.RegisterMapType((map[string]string)(nil), "sq_user_blacklist_proto.Query.OrderByEntry")
	proto.RegisterType((*PageQuery)(nil), "sq_user_blacklist_proto.PageQuery")
	proto.RegisterType((*EntityResult)(nil), "sq_user_blacklist_proto.EntityResult")
	proto.RegisterType((*ListResult)(nil), "sq_user_blacklist_proto.ListResult")
	proto.RegisterType((*PageResult)(nil), "sq_user_blacklist_proto.PageResult")
	proto.RegisterType((*SqUserBlacklistPageData)(nil), "sq_user_blacklist_proto.SqUserBlacklistPageData")
}

func init() { proto.RegisterFile("sq_user_blacklist_gen.proto", fileDescriptor_6beab68822faa327) }

var fileDescriptor_6beab68822faa327 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xef, 0x6e, 0xd3, 0x40,
	0x0c, 0x6f, 0xd2, 0xa6, 0x6b, 0xdc, 0x6a, 0x14, 0xc3, 0xb6, 0xac, 0x93, 0x46, 0x09, 0x42, 0xaa,
	0x18, 0xaa, 0x50, 0xe1, 0x03, 0x9a, 0xf8, 0xc0, 0xba, 0x76, 0x08, 0x31, 0xf1, 0xe7, 0xc6, 0x84,
	0x84, 0x40, 0x51, 0x9a, 0x1c, 0x55, 0x58, 0x9a, 0xb4, 0xc9, 0x65, 0xa2, 0x6f, 0xc1, 0x03, 0xf1,
	0x10, 0xbc, 0x0b, 0x2f, 0x80, 0xee, 0x2e, 0x74, 0xa5, 0x25, 0x5b, 0x33, 0xbe, 0x24, 0xf6, 0xfd,
	0x7c, 0xfe, 0xd9, 0x3e, 0xdb, 0xb0, 0x13, 0x4f, 0xac, 0x24, 0xa6, 0x91, 0x35, 0xf0, 0x6d, 0xe7,
	0xcc, 0xf7, 0x62, 0x66, 0x0d, 0x69, 0xd0, 0x1e, 0x47, 0x21, 0x0b, 0x71, 0x6b, 0x19, 0x14, 0x80,
	0x99, 0xc0, 0x8d, 0x93, 0xc9, 0x69, 0x4c, 0xa3, 0xee, 0x1f, 0x00, 0xd7, 0x41, 0xf5, 0x5c, 0x43,
	0x69, 0x2a, 0x2d, 0x8d, 0xa8, 0x9e, 0x8b, 0x9b, 0x50, 0xe6, 0x57, 0x3d, 0xd7, 0x50, 0xc5, 0x59,
	0xaa, 0x61, 0x03, 0x2a, 0x5c, 0x0a, 0xec, 0x11, 0x35, 0x8a, 0x4d, 0xa5, 0xa5, 0x93, 0x99, 0x8e,
	0xbb, 0x00, 0x4e, 0x44, 0x6d, 0x46, 0x99, 0x37, 0xa2, 0x46, 0x49, 0xa0, 0x73, 0x27, 0x66, 0x17,
	0xca, 0x84, 0xc6, 0x89, 0xcf, 0x10, 0xa1, 0xe4, 0x84, 0x2e, 0x4d, 0xf9, 0x84, 0x8c, 0x75, 0x28,
	0x8e, 0xe2, 0xa1, 0xa0, 0xd3, 0x09, 0x17, 0xb9, 0x95, 0x6b, 0x33, 0x3b, 0xe5, 0x11, 0xb2, 0xf9,
	0x43, 0x01, 0x3c, 0x1d, 0xbb, 0x36, 0xa3, 0x07, 0x81, 0x7b, 0x18, 0x06, 0xae, 0xc7, 0xbc, 0x30,
	0xc0, 0xe7, 0x50, 0xa6, 0x01, 0xf3, 0xd8, 0x54, 0xb8, 0xac, 0x76, 0x5a, 0xed, 0x8c, 0xdc, 0xdb,
	0x0b, 0x89, 0x93, 0xf4, 0x1e, 0x3e, 0x01, 0x6d, 0x92, 0xd0, 0x68, 0x2a, 0x02, 0xa8, 0x76, 0x76,
	0x33, 0x1d, 0xbc, 0xe3, 0x56, 0x44, 0x1a, 0x63, 0x1b, 0x6e, 0x25, 0x22, 0x1a, 0x8b, 0x8e, 0xc6,
	0x6c, 0x6a, 0x7d, 0xf1, 0xa8, 0xef, 0xc6, 0x46, 0xb1, 0x59, 0x6c, 0xe9, 0xe4, 0xa6, 0x84, 0xfa,
	0x1c, 0x39, 0x12, 0x80, 0xf9, 0x4b, 0x05, 0x4d, 0x38, 0xc0, 0x57, 0x50, 0x93, 0xcc, 0x96, 0xa4,
	0xcd, 0x1b, 0x77, 0x55, 0xde, 0x96, 0xce, 0x76, 0x40, 0x8f, 0x27, 0xbe, 0x75, 0x91, 0x80, 0x4e,
	0x2a, 0xf1, 0xc4, 0x97, 0xe0, 0x43, 0x40, 0x01, 0xfc, 0x2b, 0xc4, 0xba, 0x40, 0xe6, 0x22, 0xc4,
	0x23, 0xa8, 0x84, 0x91, 0xcb, 0x03, 0x98, 0x1a, 0xa5, 0x66, 0xb1, 0x55, 0xed, 0xec, 0x5d, 0x5e,
	0x8a, 0xf6, 0x1b, 0x6e, 0xde, 0x9d, 0xf6, 0x03, 0x16, 0x4d, 0xc9, 0x5a, 0x28, 0x35, 0xdc, 0x03,
	0xd5, 0x1d, 0x18, 0x5a, 0x53, 0x69, 0xad, 0x77, 0x76, 0x32, 0x3d, 0xf4, 0xba, 0x44, 0x75, 0x07,
	0x78, 0x17, 0x6a, 0x31, 0xf5, 0xa9, 0xc3, 0x64, 0x74, 0x46, 0x59, 0xa4, 0x50, 0x95, 0x67, 0x22,
	0xb0, 0xc6, 0x3e, 0xd4, 0xe6, 0x89, 0x78, 0xbb, 0x9c, 0x51, 0x59, 0x36, 0x9d, 0x70, 0x11, 0x6f,
	0x83, 0x76, 0x6e, 0xfb, 0x09, 0x4d, 0x0b, 0x20, 0x95, 0x7d, 0xf5, 0xa9, 0x62, 0x8e, 0x41, 0x7f,
	0x6b, 0x0f, 0xa9, 0x2c, 0xc7, 0xec, 0xa1, 0x95, 0x3c, 0x0f, 0x8d, 0x50, 0x1a, 0xdb, 0x43, 0x9a,
	0x4e, 0x83, 0x90, 0x71, 0x1b, 0x2a, 0xfc, 0x6f, 0x05, 0xc9, 0x48, 0xf4, 0xa8, 0x46, 0xd6, 0xb8,
	0xfe, 0x3a, 0x19, 0x99, 0x11, 0xd4, 0xfa, 0xe2, 0x7d, 0x72, 0x35, 0xfc, 0xb3, 0xb9, 0x86, 0xcf,
	0xd3, 0x0b, 0x72, 0x34, 0xc6, 0x00, 0xc7, 0x5c, 0xbb, 0x1e, 0x63, 0xf1, 0x1a, 0x8c, 0xdf, 0x00,
	0x78, 0x5d, 0x73, 0x31, 0xf6, 0xfe, 0xca, 0xf1, 0xd1, 0xaa, 0x8c, 0x9c, 0xa7, 0x67, 0x33, 0x3b,
	0x65, 0xfe, 0xae, 0xc0, 0x56, 0x86, 0x05, 0x6f, 0x26, 0x27, 0x89, 0x22, 0x1a, 0x30, 0x4b, 0x3c,
	0x99, 0x8c, 0xa7, 0x9a, 0x9e, 0x71, 0x33, 0xde, 0x2a, 0x4e, 0x98, 0x04, 0x2c, 0x7d, 0x4e, 0xa9,
	0xf0, 0x62, 0x70, 0x47, 0xf9, 0x8b, 0xc1, 0xbf, 0x0f, 0xb6, 0x41, 0xed, 0x75, 0xb1, 0x02, 0x25,
	0xd2, 0x3f, 0xe8, 0xd5, 0x0b, 0xa8, 0x83, 0xf6, 0x81, 0xbc, 0x7c, 0xdf, 0xaf, 0x2b, 0x9d, 0x9f,
	0x1a, 0x6c, 0x2e, 0x5c, 0x3a, 0xa1, 0xd1, 0xb9, 0xe7, 0x50, 0xfc, 0x0a, 0x1b, 0x87, 0x62, 0x43,
	0x2e, 0x2e, 0xe4, 0x95, 0xe9, 0x1b, 0xf7, 0x33, 0x2d, 0xe7, 0x5b, 0xd0, 0x2c, 0xe0, 0x10, 0x36,
	0xe4, 0xea, 0x5c, 0xe4, 0xca, 0x9e, 0xf0, 0xe5, 0x55, 0xdb, 0xb8, 0x93, 0x69, 0x3c, 0x23, 0xfa,
	0x0c, 0xf8, 0x82, 0xb2, 0x45, 0x96, 0x2b, 0x26, 0x6d, 0xf5, 0x3c, 0x2c, 0xd8, 0x5c, 0x76, 0x7f,
	0xbc, 0x0a, 0xc5, 0xbd, 0x4c, 0xfc, 0x62, 0x72, 0xcc, 0x02, 0x7e, 0x84, 0x8d, 0x1e, 0xf5, 0xe9,
	0x72, 0xa1, 0xae, 0xf2, 0xbf, 0x42, 0x6d, 0x86, 0xd0, 0x58, 0x0e, 0x9e, 0x37, 0xa5, 0x48, 0xc0,
	0xcc, 0x74, 0x30, 0x5b, 0x60, 0x97, 0x24, 0x71, 0x31, 0x8c, 0x66, 0x01, 0x3f, 0xc1, 0xd6, 0x32,
	0xd1, 0xa1, 0x68, 0xf4, 0xff, 0x4f, 0x63, 0x50, 0x16, 0xfa, 0xe3, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x03, 0x97, 0xe6, 0xaf, 0x81, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SqUserBlacklistServiceClient is the client API for SqUserBlacklistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SqUserBlacklistServiceClient interface {
	//创建
	CreateSqUserBlacklist(ctx context.Context, in *SqUserBlacklist, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明，如果要更新的是默认值 请使用update_empty_fields 大写字段数组
	UpdateSqUserBlacklist(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklist(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklistList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	DeleteSqUserBlacklist(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklistPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklistCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error)
}

type sqUserBlacklistServiceClient struct {
	cc *grpc.ClientConn
}

func NewSqUserBlacklistServiceClient(cc *grpc.ClientConn) SqUserBlacklistServiceClient {
	return &sqUserBlacklistServiceClient{cc}
}

func (c *sqUserBlacklistServiceClient) CreateSqUserBlacklist(ctx context.Context, in *SqUserBlacklist, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/CreateSqUserBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqUserBlacklistServiceClient) UpdateSqUserBlacklist(ctx context.Context, in *UpdateAndCondition, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/UpdateSqUserBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqUserBlacklistServiceClient) GetSqUserBlacklist(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EntityResult, error) {
	out := new(EntityResult)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqUserBlacklistServiceClient) GetSqUserBlacklistList(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ListResult, error) {
	out := new(ListResult)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklistList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqUserBlacklistServiceClient) DeleteSqUserBlacklist(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/DeleteSqUserBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqUserBlacklistServiceClient) GetSqUserBlacklistPageList(ctx context.Context, in *PageQuery, opts ...grpc.CallOption) (*PageResult, error) {
	out := new(PageResult)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklistPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqUserBlacklistServiceClient) GetSqUserBlacklistCount(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklistCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqUserBlacklistServiceServer is the server API for SqUserBlacklistService service.
type SqUserBlacklistServiceServer interface {
	//创建
	CreateSqUserBlacklist(context.Context, *SqUserBlacklist) (*EntityResult, error)
	//1. 按照查询条件更新，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明，如果要更新的是默认值 请使用update_empty_fields 大写字段数组
	UpdateSqUserBlacklist(context.Context, *UpdateAndCondition) (*Result, error)
	//1. 按照条件查询当个实体，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklist(context.Context, *Query) (*EntityResult, error)
	//1. 按照条件查询列表，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklistList(context.Context, *Query) (*ListResult, error)
	//1. 按照条件删除，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	DeleteSqUserBlacklist(context.Context, *Query) (*Result, error)
	//1. 按照条件查询，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklistPageList(context.Context, *PageQuery) (*PageResult, error)
	//1. 按照条件查询数量，数量值为result.data，查询可以按照实体查询和sql查询，二选一，sql查询优先使用，
	// 2.如果field对应为空值，则需要在 query_empty_fields 大写字段数组 中声明
	// 3.增加读写库查询判断
	GetSqUserBlacklistCount(context.Context, *Query) (*Result, error)
}

// UnimplementedSqUserBlacklistServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSqUserBlacklistServiceServer struct {
}

func (*UnimplementedSqUserBlacklistServiceServer) CreateSqUserBlacklist(ctx context.Context, req *SqUserBlacklist) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSqUserBlacklist not implemented")
}
func (*UnimplementedSqUserBlacklistServiceServer) UpdateSqUserBlacklist(ctx context.Context, req *UpdateAndCondition) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSqUserBlacklist not implemented")
}
func (*UnimplementedSqUserBlacklistServiceServer) GetSqUserBlacklist(ctx context.Context, req *Query) (*EntityResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSqUserBlacklist not implemented")
}
func (*UnimplementedSqUserBlacklistServiceServer) GetSqUserBlacklistList(ctx context.Context, req *Query) (*ListResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSqUserBlacklistList not implemented")
}
func (*UnimplementedSqUserBlacklistServiceServer) DeleteSqUserBlacklist(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSqUserBlacklist not implemented")
}
func (*UnimplementedSqUserBlacklistServiceServer) GetSqUserBlacklistPageList(ctx context.Context, req *PageQuery) (*PageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSqUserBlacklistPageList not implemented")
}
func (*UnimplementedSqUserBlacklistServiceServer) GetSqUserBlacklistCount(ctx context.Context, req *Query) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSqUserBlacklistCount not implemented")
}

func RegisterSqUserBlacklistServiceServer(s *grpc.Server, srv SqUserBlacklistServiceServer) {
	s.RegisterService(&_SqUserBlacklistService_serviceDesc, srv)
}

func _SqUserBlacklistService_CreateSqUserBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqUserBlacklist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).CreateSqUserBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/CreateSqUserBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).CreateSqUserBlacklist(ctx, req.(*SqUserBlacklist))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqUserBlacklistService_UpdateSqUserBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndCondition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).UpdateSqUserBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/UpdateSqUserBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).UpdateSqUserBlacklist(ctx, req.(*UpdateAndCondition))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqUserBlacklistService_GetSqUserBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklist(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqUserBlacklistService_GetSqUserBlacklistList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklistList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklistList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklistList(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqUserBlacklistService_DeleteSqUserBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).DeleteSqUserBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/DeleteSqUserBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).DeleteSqUserBlacklist(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqUserBlacklistService_GetSqUserBlacklistPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklistPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklistPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklistPageList(ctx, req.(*PageQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqUserBlacklistService_GetSqUserBlacklistCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklistCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sq_user_blacklist_proto.SqUserBlacklistService/GetSqUserBlacklistCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqUserBlacklistServiceServer).GetSqUserBlacklistCount(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _SqUserBlacklistService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sq_user_blacklist_proto.SqUserBlacklistService",
	HandlerType: (*SqUserBlacklistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSqUserBlacklist",
			Handler:    _SqUserBlacklistService_CreateSqUserBlacklist_Handler,
		},
		{
			MethodName: "UpdateSqUserBlacklist",
			Handler:    _SqUserBlacklistService_UpdateSqUserBlacklist_Handler,
		},
		{
			MethodName: "GetSqUserBlacklist",
			Handler:    _SqUserBlacklistService_GetSqUserBlacklist_Handler,
		},
		{
			MethodName: "GetSqUserBlacklistList",
			Handler:    _SqUserBlacklistService_GetSqUserBlacklistList_Handler,
		},
		{
			MethodName: "DeleteSqUserBlacklist",
			Handler:    _SqUserBlacklistService_DeleteSqUserBlacklist_Handler,
		},
		{
			MethodName: "GetSqUserBlacklistPageList",
			Handler:    _SqUserBlacklistService_GetSqUserBlacklistPageList_Handler,
		},
		{
			MethodName: "GetSqUserBlacklistCount",
			Handler:    _SqUserBlacklistService_GetSqUserBlacklistCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sq_user_blacklist_gen.proto",
}
